// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// ==================== DEBUG LOGGING ====================
const DEBUG = true;

function debugLog(category: string, message: string, data?: unknown) {
  if (!DEBUG) return;
  const timestamp = new Date().toISOString();
  const prefix = `[SUPABASE-DEBUG ${timestamp}] [${category}]`;
  if (data !== undefined) {
    console.log(prefix, message, data);
  } else {
    console.log(prefix, message);
  }
}

// Log environment on load
debugLog('ENV', '=== SUPABASE CLIENT INITIALIZATION ===');
debugLog('ENV', 'SUPABASE_URL:', SUPABASE_URL ? `${SUPABASE_URL.substring(0, 30)}...` : 'MISSING!');
debugLog('ENV', 'SUPABASE_KEY:', SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.substring(0, 20)}...` : 'MISSING!');
debugLog('ENV', 'window.location.href:', typeof window !== 'undefined' ? window.location.href : 'N/A');
debugLog('ENV', 'window.location.protocol:', typeof window !== 'undefined' ? window.location.protocol : 'N/A');
debugLog('ENV', 'window.location.origin:', typeof window !== 'undefined' ? window.location.origin : 'N/A');
debugLog('ENV', 'navigator.userAgent:', typeof navigator !== 'undefined' ? navigator.userAgent : 'N/A');
debugLog('ENV', 'navigator.onLine:', typeof navigator !== 'undefined' ? navigator.onLine : 'N/A');

// Check if we're in Tauri
const isTauri = typeof window !== 'undefined' && (
  '__TAURI__' in window ||
  '__TAURI_INTERNALS__' in window ||
  window.location.protocol === 'tauri:' ||
  (window.location.protocol === 'https:' && window.location.hostname === 'tauri.localhost')
);
debugLog('ENV', 'Is Tauri app:', isTauri);

// ==================== END DEBUG LOGGING ====================

// Validate environment variables
export function validateEnvVars(): { valid: boolean; missing: string[] } {
  const missing: string[] = [];

  if (!SUPABASE_URL) {
    missing.push('VITE_SUPABASE_URL');
  }
  if (!SUPABASE_PUBLISHABLE_KEY) {
    missing.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  }

  debugLog('VALIDATE', 'Environment validation result:', { valid: missing.length === 0, missing });

  return {
    valid: missing.length === 0,
    missing
  };
}

// Create a custom fetch that uses Tauri HTTP plugin when in Tauri
async function createTauriFetch(): Promise<typeof fetch> {
  if (!isTauri) {
    debugLog('FETCH', 'Using native fetch (not in Tauri)');
    return fetch;
  }

  debugLog('FETCH', 'Loading Tauri HTTP plugin...');

  try {
    // Dynamically import the Tauri HTTP plugin
    const { fetch: tauriFetch } = await import('@tauri-apps/plugin-http');
    debugLog('FETCH', 'Tauri HTTP plugin loaded successfully');

    // Create a wrapper that logs requests
    const wrappedFetch: typeof fetch = async (input, init) => {
      const url = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
      debugLog('FETCH', `Tauri fetch: ${init?.method || 'GET'} ${url}`);

      try {
        const response = await tauriFetch(input, init);
        debugLog('FETCH', `Tauri fetch response: ${response.status} ${response.statusText}`);
        return response;
      } catch (err) {
        const error = err as Error;
        debugLog('FETCH', `Tauri fetch error: ${error.message}`, { stack: error.stack });
        throw err;
      }
    };

    return wrappedFetch;
  } catch (err) {
    const error = err as Error;
    debugLog('FETCH', `Failed to load Tauri HTTP plugin: ${error.message}`, { stack: error.stack });
    debugLog('FETCH', 'Falling back to native fetch');
    return fetch;
  }
}

// Network connectivity test
export async function testNetworkConnectivity(): Promise<{
  success: boolean;
  supabaseReachable: boolean;
  googleReachable: boolean;
  errors: string[];
  details: Record<string, unknown>;
}> {
  debugLog('NETWORK', '=== STARTING NETWORK CONNECTIVITY TEST ===');
  const errors: string[] = [];
  const details: Record<string, unknown> = {};
  let supabaseReachable = false;
  let googleReachable = false;

  // Get the appropriate fetch function
  const customFetch = await createTauriFetch();

  // Test 1: Basic fetch to Google (simple connectivity test)
  debugLog('NETWORK', 'Test 1: Testing basic internet connectivity (google.com)...');
  try {
    const startTime = Date.now();
    const response = await customFetch('https://www.google.com/favicon.ico', {
      method: 'HEAD',
      cache: 'no-store'
    });
    const elapsed = Date.now() - startTime;
    googleReachable = true;
    details.googleTest = { success: true, elapsed, status: response.status };
    debugLog('NETWORK', `Test 1 PASSED: Google reachable in ${elapsed}ms`, { status: response.status });
  } catch (err) {
    const error = err as Error;
    errors.push(`Google fetch failed: ${error.message}`);
    details.googleTest = { success: false, error: error.message, stack: error.stack };
    debugLog('NETWORK', 'Test 1 FAILED: Google not reachable', { error: error.message, stack: error.stack });
  }

  // Test 2: Fetch Supabase health endpoint
  if (SUPABASE_URL) {
    debugLog('NETWORK', 'Test 2: Testing Supabase connectivity...');
    const healthUrl = `${SUPABASE_URL}/rest/v1/`;
    debugLog('NETWORK', 'Health URL:', healthUrl);

    try {
      const startTime = Date.now();
      const response = await customFetch(healthUrl, {
        method: 'GET',
        headers: {
          'apikey': SUPABASE_PUBLISHABLE_KEY,
          'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`
        },
        cache: 'no-store'
      });
      const elapsed = Date.now() - startTime;
      const status = response.status;
      const statusText = response.statusText;

      // Try to get response body
      let responseBody = '';
      try {
        responseBody = await response.text();
      } catch {
        responseBody = '[Could not read response body]';
      }

      supabaseReachable = response.ok || status === 401 || status === 400; // 401/400 means server responded
      details.supabaseTest = {
        success: supabaseReachable,
        elapsed,
        status,
        statusText,
        responseBody: responseBody.substring(0, 500)
      };
      debugLog('NETWORK', `Test 2 ${supabaseReachable ? 'PASSED' : 'FAILED'}: Supabase response`, details.supabaseTest);
    } catch (err) {
      const error = err as Error;
      errors.push(`Supabase fetch failed: ${error.message}`);
      details.supabaseTest = {
        success: false,
        error: error.message,
        name: error.name,
        stack: error.stack
      };
      debugLog('NETWORK', 'Test 2 FAILED: Supabase not reachable', details.supabaseTest);
    }

    // Test 3: Try Supabase Auth endpoint specifically
    debugLog('NETWORK', 'Test 3: Testing Supabase Auth endpoint...');
    const authUrl = `${SUPABASE_URL}/auth/v1/settings`;
    debugLog('NETWORK', 'Auth URL:', authUrl);

    try {
      const startTime = Date.now();
      const response = await customFetch(authUrl, {
        method: 'GET',
        headers: {
          'apikey': SUPABASE_PUBLISHABLE_KEY,
        },
        cache: 'no-store'
      });
      const elapsed = Date.now() - startTime;
      const status = response.status;

      let responseBody = '';
      try {
        responseBody = await response.text();
      } catch {
        responseBody = '[Could not read response body]';
      }

      details.supabaseAuthTest = {
        success: response.ok,
        elapsed,
        status,
        responseBody: responseBody.substring(0, 500)
      };
      debugLog('NETWORK', `Test 3 ${response.ok ? 'PASSED' : 'WARNING'}: Auth endpoint response`, details.supabaseAuthTest);
    } catch (err) {
      const error = err as Error;
      errors.push(`Supabase Auth fetch failed: ${error.message}`);
      details.supabaseAuthTest = {
        success: false,
        error: error.message,
        name: error.name,
        stack: error.stack
      };
      debugLog('NETWORK', 'Test 3 FAILED: Auth endpoint not reachable', details.supabaseAuthTest);
    }
  } else {
    errors.push('SUPABASE_URL is not configured');
    debugLog('NETWORK', 'SKIPPING Supabase tests - URL not configured');
  }

  const result = {
    success: googleReachable && supabaseReachable,
    supabaseReachable,
    googleReachable,
    errors,
    details
  };

  debugLog('NETWORK', '=== NETWORK TEST COMPLETE ===', result);
  return result;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

debugLog('CLIENT', 'Creating Supabase client...');

// Create a promise that will resolve with the configured Supabase client
let supabaseClient: ReturnType<typeof createClient<Database>> | null = null;
let supabaseClientPromise: Promise<ReturnType<typeof createClient<Database>>> | null = null;

async function initializeSupabaseClient() {
  if (supabaseClient) return supabaseClient;

  const customFetch = await createTauriFetch();

  debugLog('CLIENT', 'Creating Supabase client with custom fetch...');

  supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: customFetch
    }
  });

  debugLog('CLIENT', 'Supabase client created successfully');

  // Log auth state changes
  supabaseClient.auth.onAuthStateChange((event, session) => {
    debugLog('AUTH-STATE', `Auth state changed: ${event}`, {
      event,
      hasSession: !!session,
      userId: session?.user?.id,
      email: session?.user?.email
    });
  });

  return supabaseClient;
}

// For synchronous access, create a basic client immediately
// This will be replaced once the async initialization completes
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Initialize with Tauri fetch in the background
if (isTauri) {
  debugLog('CLIENT', 'Tauri detected, initializing with HTTP plugin...');

  // Replace the global fetch for Supabase
  (async () => {
    try {
      const { fetch: tauriFetch } = await import('@tauri-apps/plugin-http');
      debugLog('CLIENT', 'Replacing Supabase global fetch with Tauri fetch...');

      // Monkey-patch the supabase client's fetch
      // @ts-expect-error - accessing internal property
      if (supabase.rest && supabase.rest.fetch) {
        // @ts-expect-error - accessing internal property
        supabase.rest.fetch = tauriFetch;
      }

      // For auth, we need to set it globally
      // The supabase-js library uses the global fetch by default
      // We'll override window.fetch for Tauri
      const originalFetch = window.fetch;
      window.fetch = async (input, init) => {
        const url = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;

        // Only use Tauri fetch for Supabase URLs
        if (url.includes('supabase.co') || url.includes('supabase.in')) {
          debugLog('FETCH-INTERCEPT', `Using Tauri fetch for: ${url}`);
          return tauriFetch(input, init);
        }

        // Use original fetch for other URLs
        return originalFetch(input, init);
      };

      debugLog('CLIENT', 'Fetch override installed successfully');
    } catch (err) {
      const error = err as Error;
      debugLog('CLIENT', `Failed to setup Tauri fetch: ${error.message}`);
    }
  })();
}

debugLog('CLIENT', 'Supabase client exported');
